language: node_js

node_js:
- 10

branches:
  only:
  - master
  - develop

cache:
  directories:
  - node_modules

before_script:
  - npm install -g firebase-tools

jobs:
  include:

    - stage: lint
      script: npm run lint

    - stage: build
      script: npm run build -- --prod --progress=false

    - stage: deploy
      if: branch = master
      script: firebase deploy --token $FIREBASE_TOKEN
